services:
  mariadb:
    container_name: firefox_mariadb
    image: linuxserver/mariadb:10.6.13
    volumes:
      - ./data/config:/config
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql:z
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: syncstorage
      MYSQL_USER: sync
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  syncserver:
    container_name: firefox_syncserver
    build: ./app/
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    environment:
      LOGLEVEL: info
      SYNC_URL: ${SYNC_URL}
      SYNC_CAPACITY: 10 # Max number of users that will be accepted
      SYNC_MASTER_SECRET: ${SYNC_MASTER_SECRET}
      METRICS_HASH_SECRET: ${METRICS_HASH_SECRET}
      SYNC_SYNCSTORAGE_DATABASE_URL: mysql://sync:${MYSQL_PASSWORD}@${MYSQL_DOMAIN}:3306/syncstorage
      SYNC_TOKENSERVER_DATABASE_URL: mysql://sync:${MYSQL_PASSWORD}@${MYSQL_DOMAIN}:3306/tokenserver
